# generate_profile_fixture.R
# ::rtemis::
# 2026- EDG rtemis.org

# `profile/v1/fixture.json` and the Parquet files it names -- the documents that
# hold the three profile emitters to one answer.
#
# `checks/v1/corpus.json` cannot do this job. Profiles are *inputs* to the
# corpus, so a rule evaluated identically by every host still gives the wrong
# answer if the hosts described the dataset differently. Nothing else compares
# rtemis's `data_profile()`, the CLI's polars profiler and rtemislive's DuckDB
# one.
#
# **Parquet, not a delimited file.** A delimited file carries no types, so each
# reader infers them and the fixture would be testing three type inferences
# rather than three profilers -- and the inferences legitimately differ, which
# is why an ingest step exists to settle them once. Parquet *declares* its
# types, so every host reads the same declaration and a disagreement is a real
# disagreement.
#
# The data is published beside this document rather than inside it. A fixture
# that embedded its dataset would be a mechanism that only works while the
# dataset is small, and would invite someone to point it at one that is not.
# Each case names its file and records the sha256 a consumer must verify --
# the same shape as the wasm module's manifest.

suppressMessages(pkgload::load_all(
  rprojroot::find_package_root_file(),
  quiet = TRUE
))
check_dependencies("arrow")

out_dir <- commandArgs(trailingOnly = TRUE)[[1L]]
base_url <- "https://schema.rtemis.org"
rel_dir <- file.path("profile", "v1", "fixtures")

# %% The cases ----

# Every dtype the vocabulary can hold, plus the shapes a check reads: a gap in a
# number and in an integer, a factor that carries level counts, a constant, and
# two rows that repeat an earlier one. A `factor` is what makes this Parquet
# carry a dictionary column, which is the one type a delimited file cannot say.
.mixed <- local({
  set.seed(2026L)
  n <- 24L
  d <- data.frame(
    x_num = c(NA, seq_len(n - 1L) * 1.25),
    x_int = c(NA_integer_, rep_len(0:6, n - 1L)),
    g = factor(rep_len(c("alpha", "beta", "gamma"), n)),
    flag = rep_len(c(TRUE, FALSE), n),
    when = as.Date("2026-01-01") + rep_len(0:27, n),
    note = rep_len(c("free text one", "free text two"), n),
    const = factor(rep_len("k", n))
  )
  rbind(d, d[1L, ], d[1L, ])
})

# `id` is above `PROFILE_MAX_LEVELS` and carries no level counts; `grp` beside it
# is below and does. The bound is what keeps the document a description rather
# than a copy of the column, and having both here shows it is applied per column
# rather than to the table.
.wide <- local({
  n <- PROFILE_MAX_LEVELS + 6L
  data.frame(
    id = factor(sprintf("id%03d", seq_len(n))),
    grp = factor(rep_len(c("a", "b"), n)),
    y = rep_len(0:2, n)
  )
})

cases <- list(
  list(
    id = "every dtype, with gaps, a constant and duplicate rows",
    file = "mixed.parquet",
    data = .mixed
  ),
  list(
    id = "a column above PROFILE_MAX_LEVELS carries no level counts",
    file = "wide.parquet",
    data = .wide
  )
)

# %% Write and measure ----

sha256 <- function(path) {
  paste(
    as.character(openssl::sha256(readBin(path, "raw", file.size(path)))),
    collapse = ""
  )
}

dir.create(file.path(out_dir, rel_dir), recursive = TRUE, showWarnings = FALSE)

measure <- function(case) {
  path <- file.path(out_dir, rel_dir, case[["file"]])
  arrow::write_parquet(case[["data"]], path)
  list(
    id = case[["id"]],
    # Registry-relative, which is what a consumer knows a document by.
    data = paste(rel_dir, case[["file"]], sep = "/"),
    sha256 = sha256(path),
    profile = to_json(data_profile(read(path, verbosity = 0L)))
  )
}

doc <- list(
  `$id` = paste0(base_url, "/profile/v1/fixture.json"),
  title = "rtemis profile conformance fixture",
  description = paste0(
    "One Parquet file per case and the `profile/v1` document rtemis measures ",
    "for it. Every implementation of the profile reads the same file and must ",
    "produce the same document. Parquet because it declares its types: a ",
    "delimited file would make this a test of three type inferences rather ",
    "than of three profilers. Generated by rtemis; never edited downstream."
  ),
  rtemis_version = as.character(utils::packageVersion("rtemis")),
  profile_max_levels = PROFILE_MAX_LEVELS,
  cases = lapply(cases, measure)
)

json <- jsonlite::toJSON(
  doc,
  auto_unbox = TRUE,
  pretty = TRUE,
  na = "null",
  null = "null"
)
writeLines(json, file.path(out_dir, "profile", "v1", "fixture.json"))

# Also written to `inst/`, so the package carries the artifacts it publishes:
# `data-raw/` is in `.Rbuildignore`, and the test that reproduces the fixture
# has to read them on CRAN.
inst_dir <- rprojroot::find_package_root_file("inst", "profile")
dir.create(
  file.path(inst_dir, "fixtures"),
  recursive = TRUE,
  showWarnings = FALSE
)
writeLines(json, file.path(inst_dir, "fixture.json"))
for (case in cases) {
  file.copy(
    file.path(out_dir, rel_dir, case[["file"]]),
    file.path(inst_dir, "fixtures", case[["file"]]),
    overwrite = TRUE
  )
}

cat(sprintf(
  "profile fixture  %d cases + %d parquet -> %s\n",
  length(cases),
  length(cases),
  file.path(out_dir, "profile", "v1", "fixture.json")
))
